version: '2'
services:
    host:
        build:
            context: ./docker
            dockerfile: Dockerfile-host
        links:
            - remote1
        volumes:
            - ./ansible:/etc/ansible
        tty: true

    remote1:
        build:
            context: ./docker
            dockerfile: Dockerfile-remote
        tty: true

    remote2:
        build:
            context: ./docker
            dockerfile: Dockerfile-remote
        tty: true

    remote3:
        build:
            context: ./docker
            dockerfile: Dockerfile-remote
        tty: true
