version: '2'
services:
    host:
        build:
            context: ./docker
            dockerfile: Dockerfile-host
        links:
            - remote1
        volumes:
            - ./ansible:/etc/ansible
        environment:
            - ansible_python_interpreter=/usr/local/bin/python
        tty: true

    remote1:
        build:
            context: ./docker
            dockerfile: Dockerfile-remote
        environment:
            - ansible_python_interpreter=/usr/local/bin/python
        tty: true
