FROM alpine:edge

RUN apk update && \
    apk add --no-cache openssh python3 && \
    mkdir /root/.ssh && chmod 700 /root/.ssh

ADD sshd_config /etc/ssh/sshd_config

ADD remote1.pub /root/.ssh/authorized_keys
RUN chmod 600 /root/.ssh/authorized_keys

EXPOSE 22
RUN ssh-keygen -A
CMD ["/usr/sbin/sshd", "-D"]
